name: Auto Assign and Unassign on /assign or /unassign

permissions:
  issues: write

on:
  issue_comment:
    types: [created]

jobs:
  manage-assignment:
    runs-on: ubuntu-latest
    outputs:
      issue_number: ${{ steps.process-assignment.outputs.issue_number }}
      action: ${{ steps.process-assignment.outputs.action }}
      should_update: ${{ steps.process-assignment.outputs.should_update }}
    steps:
      - name: Process assignment comment only if command is used
        if: startsWith(github.event.comment.body, '/assign') || startsWith(github.event.comment.body, '/unassign')
        uses: actions/github-script@v6
        id: process-assignment
        with:
          script: |
            const commentBody = context.payload.comment.body.trim();
            const issueNumber = context.payload.issue.number;
            const username = context.payload.comment.user.login;
            let action = '';
            let shouldUpdate = false;

            if (commentBody === '/assign') {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                assignees: [username]
              });
              console.log(`Assigned ${username} to issue #${issueNumber}`);
              action = 'assigned';
              shouldUpdate = true;
            } else if (commentBody === '/unassign') {
              await github.rest.issues.removeAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                assignees: [username]
              });
              console.log(`Unassigned ${username} from issue #${issueNumber}`);
              action = 'unassigned';
              shouldUpdate = true;
            } else {
              console.log("Comment does not exactly match '/assign' or '/unassign'");
            }
            
            core.setOutput('issue_number', issueNumber.toString());
            core.setOutput('action', action);
            core.setOutput('should_update', shouldUpdate.toString());

  assign-status-sync:
    needs: manage-assignment
    if: needs.manage-assignment.outputs.should_update == 'true'
    uses: ./.github/workflows/assign-status-sync.yml
    with:
      issue_number: ${{ needs.manage-assignment.outputs.issue_number }}
      action: ${{ needs.manage-assignment.outputs.action }}
    secrets:
      PJ_APP_ID: ${{ secrets.PJ_APP_ID }}
      PJ_APP_PEM: ${{ secrets.PJ_APP_PEM }}
