name: Sync Project Status with Assignees

on:
  issues:
    types: [assigned, unassigned]

permissions:
  issues: read

jobs:
  update_status:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
    - name: Generate token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.PJ_APP_ID }}
        private-key: ${{ secrets.PJ_APP_PEM }}
        owner: ${{ github.repository_owner }}
        repositories: |
          kouchou-ai-copy

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements.txt
        
    - name: Update Status based on Assignment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_TOKEN: ${{ steps.generate-token.outputs.token }}
        PROJECT_ID: ${{ vars.PROJECT_ID }}
        STATUS_FIELD: ${{ vars.STATUS_FIELD }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
        GITHUB_EVENT_ACTION: ${{ github.event.action }}
      run: |
        python .github/scripts/assignee_status_sync.py
