name: Sync Project Status with Progress

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]

permissions:
  issues: read
  contents: read
  pull-requests: read

jobs:
  update_status:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: >
      (github.event_name == 'issue_comment' && !github.event.issue.pull_request) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body || '', '#'))

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/requirements.txt

    - name: Update Status based on Progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        STATUS_FIELD: ${{ secrets.STATUS_FIELD }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        python .github/scripts/progress_status_sync.py
